<a href="https://colab.research.google.com/github/varsha-kotegar/Machine-Learning-Course/blob/main/Complete_Numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy-Numerical Python

Advantages of NumPy Arrays:
1. Allows several Mathematical Operations
2. Faster operations

faster operations can be done compared to others

In [ ]:
import numpy as np

List vs NumPy - Time taken

In [ ]:
from time import process_time

Time taken in list

In [ ]:
python_list = [i for i in range(10000)]

start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()

print(end_time - start_time)

0.0009827250000000731


In [ ]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()
np_array += 5
end_time = process_time()

print(end_time - start_time)

0.0001784560000004376


#NumPy Arrays

nd - n dimenstion

In [ ]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
#creating a 1 D array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

In [ ]:
b= np.array([(1,2,3,4),(5,6,7,8)])
print(b)
b.shape #2 - rows, 4- columns

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [ ]:
c= np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


#Initial Placeholders in NumPy arrays

In [ ]:
#create a numpy of zeros
x= np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#array of a particular values
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
z2 = np.full((2,3),6)
print(z2)

[[6 6 6]
 [6 6 6]]


In [ ]:
#create an identity matrix - no. of rows n cols are equal
a = np.eye(3)
print(a)
b= np.eye(5)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
#create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.85751948 0.15272026 0.60285709 0.44059666]
 [0.9069737  0.61551335 0.34421245 0.24756038]
 [0.62116509 0.74919245 0.15137985 0.28013137]]


In [ ]:
#random integer values array with specific range
c = np.random.randint(5,10,(2,3))
print(c)

[[9 7 6]
 [5 6 8]]


In [ ]:
#array of evenly spaced values, here 6 is numbber of values I want
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [ ]:
#array of evenly spaced values --> spacing the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [ ]:
#Covert a list to numpy array
list2 = [10,20,30,40,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

#Analysing a numpy array

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

[[25 73 10 34 46]
 [52 22 57 88 41]
 [75 15 23 87 45]
 [44 27 35 33 17]
 [79 26 49 42 72]]


In [ ]:
#array dimensions
c.shape

(5, 5)

In [ ]:
#number of dimensions
print(c.ndim)

2


In [ ]:
#number of elements in an array
print(c.size)

25


In [ ]:
#checking the data types of values in the array
print(c.dtype)

int64


Mathematical operations on np array

In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(  list1 + list2) #concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

print(a)

[[7 3 7]
 [2 4 9]
 [4 8 3]]


In [ ]:
print(b)

[[17 18 14]
 [10 17 17]
 [18 17 12]]


In [ ]:
print(a+b)

[[24 21 21]
 [12 21 26]
 [22 25 15]]


In [ ]:
print(a-b)
print(a*b)
print(a/b)

[[-10 -15  -7]
 [ -8 -13  -8]
 [-14  -9  -9]]
[[119  54  98]
 [ 20  68 153]
 [ 72 136  36]]
[[0.41176471 0.16666667 0.5       ]
 [0.2        0.23529412 0.52941176]
 [0.22222222 0.47058824 0.25      ]]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

print(a)
print(b)

[[4 5 5]
 [1 3 3]
 [4 9 3]]
[[16 11 10]
 [11 16 18]
 [12 13 10]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[20 16 15]
 [12 19 21]
 [16 22 13]]
[[-12  -6  -5]
 [-10 -13 -15]
 [ -8  -4  -7]]
[[ 64  55  50]
 [ 11  48  54]
 [ 48 117  30]]
[[0.25       0.45454545 0.5       ]
 [0.09090909 0.1875     0.16666667]
 [0.33333333 0.69230769 0.3       ]]


#Array Manipulation

In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)

print(array.shape)

[[6 0 0]
 [0 0 7]]
(2, 3)


In [ ]:
#transpose - rows to cols <-> cols to rows
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[6 0]
 [0 0]
 [0 7]]
(3, 2)


In [ ]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[6 0]
 [0 0]
 [0 7]]
(3, 2)


In [ ]:
#reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[0 2 7]
 [1 3 8]]
(2, 3)


In [ ]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[0 2]
 [7 1]
 [3 8]]
(3, 2)
